name: Deploy to Cloudways

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
    
    - name: Validate PHP syntax
      run: |
        find . -name "*.php" -exec php -l {} \; | grep -v "No syntax errors"
    
    - name: Check file permissions
      run: |
        find . -name "*.php" -exec chmod 644 {} \;
        find . -type d -exec chmod 755 {} \;

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Cloudways via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.CLOUDWAYS_HOST }}
        username: ${{ secrets.CLOUDWAYS_USERNAME }}
        key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
        port: ${{ secrets.CLOUDWAYS_PORT || 22 }}
        script: |
          # Navigate to WordPress plugins directory
          cd ${{ secrets.WORDPRESS_PATH }}/wp-content/plugins/
          
          # Backup existing plugin if it exists
          if [ -d "maintenance-signature-system" ]; then
            mv maintenance-signature-system maintenance-signature-system.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Clone the latest version
          git clone https://github.com/${{ github.repository }}.git maintenance-signature-system
          
          # Set proper permissions
          find maintenance-signature-system -name "*.php" -exec chmod 644 {} \;
          find maintenance-signature-system -type d -exec chmod 755 {} \;
          
          # Remove .git directory for security
          rm -rf maintenance-signature-system/.git
          
          echo "Deployment completed successfully!"

  backup:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Create database backup via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.CLOUDWAYS_HOST }}
        username: ${{ secrets.CLOUDWAYS_USERNAME }}
        key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
        port: ${{ secrets.CLOUDWAYS_PORT || 22 }}
        script: |
          # Create backup directory
          mkdir -p ${{ secrets.BACKUP_PATH }}/$(date +%Y-%m-%d)
          
          # Database backup
          mysqldump -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} > ${{ secrets.BACKUP_PATH }}/$(date +%Y-%m-%d)/maintenance_system_backup_$(date +%Y%m%d_%H%M%S).sql
          
          # Keep only last 7 days of backups
          find ${{ secrets.BACKUP_PATH }} -type d -mtime +7 -exec rm -rf {} \;
          
          echo "Backup completed successfully!"